services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/qoentz/evedict:latest
    container_name: evedict-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
    volumes:
      - .:/app
    networks:
      - evedict_network

  db:
    image: postgres:latest
    container_name: evedict-db
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - evedict_db_data:/var/lib/postgresql/data
    networks:
      - evedict_network

networks:
  evedict_network:

volumes:
  evedict_db_data:
