version: '3.8'
services:
  app:
    build: .
    container_name: evedict
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db  # The service name of the Postgres container
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
    networks:
      - evedict_network

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5433:5432"  # Maps Postgres' port to localhost
    volumes:
      - evedict_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - evedict_network

networks:
  evedict_network:

volumes:
  evedict_db_data:
